name: docker build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 

      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -  
      name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
        .
